import { hexWithoutHash, resolvedColumnStyle } from "../design";
import { ExportRenderOptions, ExportTextAlign } from "../types";
import { displayValue, filterSummary, PreparedExport } from "./common";

export async function docxBlob(exportData: PreparedExport, renderOptions: ExportRenderOptions) {
  if (exportData.rows.length > 5_000) throw new Error("DOCX is limited to 5,000 rows. Narrow the filters or choose a data format.");
  const {
    AlignmentType, Document, HeightRule, PageOrientation, Packer, Paragraph,
    ShadingType, Table, TableCell, TableRow, TextRun, WidthType,
  } = await import("docx");
  const landscape = exportData.columns.length > 6;
  const alignment = (value: ExportTextAlign) => value === "left" ? AlignmentType.LEFT : value === "right" ? AlignmentType.RIGHT : AlignmentType.CENTER;
  const cell = (value: string, columnKey: string, header = false) => {
    const style = resolvedColumnStyle(renderOptions.tableStyle, renderOptions.columnStyles[columnKey]);
    return new TableCell({
      shading: { type: ShadingType.CLEAR, fill: hexWithoutHash(header ? style.headerBackground : style.bodyBackground), color: "auto" },
      children: [new Paragraph({ children: [new TextRun({ text: value, bold: header, color: hexWithoutHash(header ? style.headerText : style.bodyText), size: renderOptions.tableStyle.fontSize * 2 })] })],
    });
  };
  const rowHeight = { value: Math.round(renderOptions.tableStyle.rowHeight * 20), rule: HeightRule.ATLEAST };
  const table = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ tableHeader: true, height: rowHeight, children: exportData.columns.map((column) => cell(column.label, column.key, true)) }),
      ...exportData.rows.map((row) => new TableRow({ height: rowHeight, children: exportData.columns.map((column) => cell(displayValue(row[column.key]), column.key)) })),
    ],
  });
  const titleParagraphs = renderOptions.titleLines.filter((line) => line.text.trim()).map((line) => new Paragraph({
    alignment: alignment(line.align),
    spacing: { after: 180 },
    children: [new TextRun({ text: line.text, bold: !line.sourceColumnKey, color: hexWithoutHash(line.color), size: line.fontSize * 2 })],
  }));
  const metadataLines = [
    `Generated: ${new Date(exportData.dataset.metadata.generatedAt).toLocaleString()}`,
    `Generated by: ${exportData.dataset.metadata.generatedBy}`,
    `Rows: ${exportData.dataset.total}`,
    `Filters: ${filterSummary(exportData.dataset)}`,
  ];
  const metadataParagraphs = [
    new Paragraph({ spacing: { before: 220, after: 80 }, children: [new TextRun({ text: "Metadata", bold: true, size: 17 })] }),
    ...metadataLines.map((text) => new Paragraph({ spacing: { after: 40 }, children: [new TextRun({ text, size: 15, color: "4B4B4B" })] })),
  ];
  const document = new Document({ sections: [{
    properties: { page: { size: { orientation: landscape ? PageOrientation.LANDSCAPE : PageOrientation.PORTRAIT } } },
    children: [
      ...titleParagraphs,
      new Paragraph(""), table,
      ...metadataParagraphs,
    ],
  }] });
  return Packer.toBlob(document);
}