import jsPDF from "jspdf";
import { autoTable } from "jspdf-autotable";
import { DocHeader, DocHeaderSec } from "../../../data/branding";
import { loadPdfImage } from "../../../utils/pdf";
import { hexToRgb, resolvedColumnStyle } from "../design";
import { ExportRenderOptions } from "../types";
import { displayValue, filterSummary, PreparedExport } from "./common";

export type PdfOrientation = "auto" | "portrait" | "landscape";

export async function pdfBlob(exportData: PreparedExport, renderOptions: ExportRenderOptions) {
  if (exportData.rows.length > 5_000) throw new Error("PDF is limited to 5,000 rows. Narrow the filters or choose a data format.");
  const orientation = renderOptions.pdfOrientation === "auto"
    ? (exportData.columns.length > 6 ? "landscape" : "portrait")
    : renderOptions.pdfOrientation;
  const doc = new jsPDF({ orientation, unit: "mm", format: "a4" });
  const firstTemplate = renderOptions.includeBrandHeader ? await loadPdfImage(DocHeader) : null;
  const continuationTemplate = renderOptions.includeBrandHeader ? await loadPdfImage(DocHeaderSec) : null;
  const baseY = renderOptions.includeBrandHeader ? (orientation === "portrait" ? 62 : 24) : 12;
  const titleLines = renderOptions.titleLines.filter((line) => line.text.trim());
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxTextWidth = pageWidth - 20;
  const titleGap = 3;

  const addBackground = (pageNumber: number) => {
    if (!renderOptions.includeBrandHeader) return;
    const image = pageNumber === 1 ? firstTemplate : continuationTemplate;
    if (!image) return;
    const imageRatio = 1052 / 1503;
    const pageRatio = pageWidth / pageHeight;
    let width = pageWidth; let height = pageHeight; let x = 0; let y = 0;
    if (imageRatio > pageRatio) { width = pageHeight * imageRatio; x = (pageWidth - width) / 2; }
    else { height = pageWidth / imageRatio; y = (pageHeight - height) / 2; }
    doc.addImage(image, "PNG", x, y, width, height, undefined, "FAST");
  };

  const titleHeight = titleLines.reduce((sum, line) => {
    doc.setFontSize(line.fontSize);
    const wrapped = doc.splitTextToSize(line.text, maxTextWidth) as string[];
    return sum + Math.max(4, wrapped.length * line.fontSize * 0.43) + titleGap;
  }, 0);
  const tableY = baseY + titleHeight + 5;

  const drawFooter = (pageNumber: number) => {
    doc.setFontSize(8); doc.setTextColor(80, 80, 80);
    doc.text(`Page ${pageNumber}`, pageWidth - 10, pageHeight - 7, { align: "right" });
  };

  autoTable(doc, {
    head: [exportData.columns.map((column) => column.label)],
    body: exportData.rows.map((row) => exportData.columns.map((column) => displayValue(row[column.key]))),
    startY: tableY,
    margin: { top: tableY, bottom: 42, left: 9, right: 9 },
    theme: "grid",
    styles: { fontSize: renderOptions.tableStyle.fontSize, cellPadding: 1.7, overflow: "linebreak", valign: "middle", minCellHeight: renderOptions.tableStyle.rowHeight * 0.3528 },
    headStyles: { fontStyle: "bold" },
    didParseCell: (data) => {
      const column = exportData.columns[data.column.index];
      if (!column) return;
      const style = resolvedColumnStyle(renderOptions.tableStyle, renderOptions.columnStyles[column.key]);
      data.cell.styles.fillColor = hexToRgb(data.section === "head" ? style.headerBackground : style.bodyBackground);
      data.cell.styles.textColor = hexToRgb(data.section === "head" ? style.headerText : style.bodyText);
      data.cell.styles.fontSize = renderOptions.tableStyle.fontSize;
      data.cell.styles.minCellHeight = renderOptions.tableStyle.rowHeight * 0.3528;
    },
    willDrawPage: ({ pageNumber }) => {
      addBackground(pageNumber);
      let y = baseY;
      for (const line of titleLines) {
        doc.setFont("helvetica", line.sourceColumnKey ? "normal" : "bold");
        doc.setFontSize(line.fontSize);
        doc.setTextColor(...hexToRgb(line.color));
        const wrapped = doc.splitTextToSize(line.text, maxTextWidth) as string[];
        const x = line.align === "left" ? 10 : line.align === "right" ? pageWidth - 10 : pageWidth / 2;
        doc.text(wrapped, x, y, { align: line.align, maxWidth: maxTextWidth, lineHeightFactor: 1.15 });
        y += Math.max(4, wrapped.length * line.fontSize * 0.43) + titleGap;
      }
    },
    didDrawPage: ({ pageNumber }) => drawFooter(pageNumber),
  });

  const finalTableY = (doc as typeof doc & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? tableY;
  const metadataLines = [
    `Generated: ${new Date(exportData.dataset.metadata.generatedAt).toLocaleString()}`,
    `Generated by: ${exportData.dataset.metadata.generatedBy}`,
    `Rows: ${exportData.dataset.total}`,
    `Filters: ${filterSummary(exportData.dataset)}`,
  ];
  const wrappedMetadata = metadataLines.map((line) => doc.splitTextToSize(line, maxTextWidth) as string[]);
  const metadataHeight = 7 + wrappedMetadata.reduce((height, lines) => height + lines.length * 3.5, 0);
  let metadataY = finalTableY + 7;
  if (metadataY + metadataHeight > pageHeight - 10) {
    doc.addPage();
    addBackground(doc.getNumberOfPages());
    drawFooter(doc.getNumberOfPages());
    metadataY = renderOptions.includeBrandHeader ? (orientation === "portrait" ? 62 : 24) : 12;
  }
  doc.setFont("helvetica", "bold"); doc.setFontSize(8.5); doc.setTextColor(45, 45, 45);
  doc.text("Metadata", 10, metadataY);
  doc.setFont("helvetica", "normal"); doc.setFontSize(7.5); doc.setTextColor(75, 75, 75);
  let metadataLineY = metadataY + 5;
  for (const lines of wrappedMetadata) {
    doc.text(lines, 10, metadataLineY, { lineHeightFactor: 1.15 });
    metadataLineY += lines.length * 3.5;
  }
  return doc.output("blob");
}