import { hexWithoutHash, resolvedColumnStyle } from "../design";
import { ExportRenderOptions } from "../types";
import { filterSummary, PreparedExport, spreadsheetSafe } from "./common";

export async function xlsxBlob(exportData: PreparedExport, renderOptions: ExportRenderOptions) {
  const ExcelJS = await import("exceljs");
  const workbook = new ExcelJS.Workbook();
  workbook.creator = exportData.dataset.metadata.generatedBy;
  workbook.created = new Date(exportData.dataset.metadata.generatedAt);
  workbook.subject = `${exportData.dataset.metadata.reportName} | ${filterSummary(exportData.dataset)}`;
  const sheet = workbook.addWorksheet(exportData.dataset.metadata.reportName.slice(0, 31));
  sheet.columns = exportData.columns.map((column) => ({ key: column.key, width: Math.min(45, Math.max(12, column.label.length + 4)) }));

  const titleLines = renderOptions.titleLines.filter((line) => line.text.trim());
  for (const line of titleLines) {
    const row = sheet.addRow([line.text]);
    if (exportData.columns.length > 1) sheet.mergeCells(row.number, 1, row.number, exportData.columns.length);
    const cell = row.getCell(1);
    cell.font = { bold: !line.sourceColumnKey, color: { argb: `FF${hexWithoutHash(line.color)}` }, size: line.fontSize };
    cell.alignment = { horizontal: line.align, vertical: "middle", wrapText: true };
    row.height = Math.max(renderOptions.tableStyle.rowHeight, line.fontSize * 2.1);
  }

  const headerRow = sheet.addRow(exportData.columns.map((column) => column.label));
  headerRow.height = renderOptions.tableStyle.rowHeight;
  exportData.columns.forEach((column, index) => {
    const style = resolvedColumnStyle(renderOptions.tableStyle, renderOptions.columnStyles[column.key]);
    const cell = headerRow.getCell(index + 1);
    cell.font = { bold: true, color: { argb: `FF${hexWithoutHash(style.headerText)}` }, size: renderOptions.tableStyle.fontSize };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${hexWithoutHash(style.headerBackground)}` } };
    cell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
  });

  for (const data of exportData.rows) {
    const row = sheet.addRow(exportData.columns.map((column) => column.valueType === "number" && typeof data[column.key] === "number" ? data[column.key] : spreadsheetSafe(data[column.key])));
    row.height = renderOptions.tableStyle.rowHeight;
    exportData.columns.forEach((column, index) => {
      const style = resolvedColumnStyle(renderOptions.tableStyle, renderOptions.columnStyles[column.key]);
      const cell = row.getCell(index + 1);
      cell.font = { color: { argb: `FF${hexWithoutHash(style.bodyText)}` }, size: renderOptions.tableStyle.fontSize };
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: `FF${hexWithoutHash(style.bodyBackground)}` } };
      cell.alignment = { vertical: "top", wrapText: true };
    });
  }
  sheet.views = [{ state: "frozen", ySplit: headerRow.number }];
  if (exportData.rows.length) sheet.autoFilter = { from: { row: headerRow.number, column: 1 }, to: { row: headerRow.number + exportData.rows.length, column: exportData.columns.length } };
  sheet.addRow([]).height = 8;
  const metadataRows = [
    ["Metadata", true],
    [`Generated: ${new Date(exportData.dataset.metadata.generatedAt).toLocaleString()}`, false],
    [`Generated by: ${exportData.dataset.metadata.generatedBy}`, false],
    [`Rows: ${exportData.dataset.total}`, false],
    [`Filters: ${filterSummary(exportData.dataset)}`, false],
  ] as const;
  for (const [text, bold] of metadataRows) {
    const row = sheet.addRow([text]);
    if (exportData.columns.length > 1) sheet.mergeCells(row.number, 1, row.number, exportData.columns.length);
    row.getCell(1).font = { bold, color: { argb: "FF4B4B4B" }, size: bold ? 9 : 8 };
    row.getCell(1).alignment = { vertical: "middle", wrapText: true };
  }
  const buffer = await workbook.xlsx.writeBuffer();
  return new Blob([buffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
}